### PR TITLE
Explicit comment about proxy and proxy owner

### LINKED ISSUE #8: Owner can rugpull hard with upgrade
This contract is using upgradable logic. This means that the owner can deploy a new contract at any time and take every NFT and all authorized payment tokens owned by everybody that has listed NFTs for sale on the marketplace.

This may be an economically feasible rugpull strategy. And the feasibility of this rugpull increases as time goes on.

Such a risk may not be obvious to participants of the smart contract. And so for them this is an unknown risk.

**Recommendation**: this risk should be explicitly disclosed at the top of the contract (in a `@notice` or `@dev` NatSpec entry) and in any documentation for people using the contract.

### PR DESCRIPTION
**Pull request by ghoul-sol**
Fixes #8

### CODE REVIEW

**Comment by fulldecent** [comment]
Preparing a competing PR that is much more explicit about the risks.

**Comment by fulldecent** [comment]
Alternate version is at the end of `fix-everything` branch.

**Comment by ghoul-sol** [comment]
Here's the approved version:
```
// Please note that this contract is upgradeable. In the event of a compromised ProxyAdmin contract owner, collectible tokens and payments may be at risk.
// To prevent this, the ProxyAdmin is owned by a multi-sig governed by the TreasureDAO council.
```

I'll update this PR.

**Review by fulldecent — APPROVED** [review]
Looks good!

**Pull request merged**
